-- wezterm.lua — lnx-cli-tui-ide
-- WezTerm is the fallback terminal for machines whose GPU cannot do OpenGL 3.3.
-- It runs in software-rendering mode and still speaks the kitty graphics protocol,
-- so euporie inline plots keep working.
--
-- Per-machine values (scrollback sized to RAM) live in local.lua, generated by
-- the installer and merged here if present. Never edit local.lua in the repo.

local wezterm = require 'wezterm'
local config = wezterm.config_builder and wezterm.config_builder() or {}

-- ---- Software rendering (the whole reason WezTerm is the fallback) ---------
config.front_end = 'Software'
config.webgpu_power_preference = 'LowPower'

-- ---- Font ------------------------------------------------------------------
-- JetBrainsMono Nerd Font for the icons used by yazi and lazygit.
config.font = wezterm.font_with_fallback {
  'JetBrainsMono Nerd Font',
  'JetBrains Mono',
  'monospace',
}
config.font_size = 12.0

-- ---- Calm dark theme tuned for long sessions -------------------------------
-- Based on the "Tomorrow Night" scheme by Chris Kempson (MIT); mirrors kitty.conf.
config.colors = {
  foreground = '#c5c8c6',
  background = '#1d1f21',
  cursor_bg = '#c5c8c6',
  cursor_fg = '#1d1f21',
  selection_fg = '#1d1f21',
  selection_bg = '#c5c8c6',
  ansi = { '#1d1f21', '#cc6666', '#b5bd68', '#f0c674', '#81a2be', '#b294bb', '#8abeb7', '#c5c8c6' },
  brights = { '#969896', '#d54e53', '#b9ca4a', '#e7c547', '#7aa6da', '#c397d8', '#70c0b1', '#eaeaea' },
}

-- ---- Window & behavior -----------------------------------------------------
config.window_padding = { left = 6, right = 6, top = 6, bottom = 6 }
config.hide_tab_bar_if_only_one_tab = true
config.use_fancy_tab_bar = false
config.audible_bell = 'Disabled'
config.check_for_updates = false
config.adjust_window_size_when_changing_font_size = false

-- ---- Scrollback ------------------------------------------------------------
-- Base value; overridden by local.lua (installer sizes it to RAM).
config.scrollback_lines = 10000

-- ---- Merge machine-local overrides (scrollback, etc.) ----------------------
local ok, localcfg = pcall(require, 'local')
if ok and type(localcfg) == 'table' then
  for k, v in pairs(localcfg) do
    config[k] = v
  end
end

return config
